apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

replicas:
- name: worker
  count: 1

images:
- name: schoolofdevops/worker
  newTag: latest

namespace: instavote

commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supported-by: "sre@example.com"

